// Generate seed.sql from the bundled source data in scripts/seed-source/.
// Output: 17 portals, one archived week, 17 sample captures (r2_key NULL => served from /samples).
// Self-contained: uses paths relative to this file, so it runs on any machine.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SRC = join(__dirname, "seed-source");
const OUT = join(__dirname, "..", "seed.sql");

const portalsCfg = JSON.parse(readFileSync(join(SRC, "portals.json"), "utf8"));
const manifest = JSON.parse(readFileSync(join(SRC, "manifest.json"), "utf8"));

const portals = Array.isArray(portalsCfg) ? portalsCfg : portalsCfg.portals || [];
const captures = Array.isArray(manifest) ? manifest : manifest.captures || manifest.items || [];

const q = (v) =>
  v === null || v === undefined ? "NULL" : `'${String(v).replace(/'/g, "''")}'`;

function weekLabel(iso) {
  const d = new Date(iso + "T00:00:00Z");
  const m = d.toLocaleString("en-US", { month: "short", timeZone: "UTC" });
  return `Week of ${m} ${d.getUTCDate()}, ${d.getUTCFullYear()}`;
}

const lines = [];
lines.push("-- Auto-generated by scripts/gen-seed.mjs from scripts/seed-source/. Do not edit by hand.");
lines.push("-- Seeds the portal catalog + one sample week so the gallery renders before the first real capture.");
lines.push("");

portals.forEach((p, i) => {
  lines.push(
    `INSERT INTO portals (slug,name,company,url,brand,wait_for,full_page,active,sort_order) VALUES (` +
      `${q(p.slug)},${q(p.name)},${q(p.company)},${q(p.url)},${q(p.brand)},` +
      `${Number(p.waitFor ?? 4000)},${p.fullPage ? 1 : 0},1,${i});`
  );
});
lines.push("");

const weeks = [...new Set(captures.map((c) => c.week))];
weeks.forEach((w) => {
  const okCount = captures.filter((c) => c.week === w && (c.status ?? "ok") === "ok").length;
  lines.push(
    `INSERT INTO weeks (week,label,created_at,portal_count) VALUES (` +
      `${q(w)},${q(weekLabel(w))},${q(new Date().toISOString())},${okCount});`
  );
});
lines.push("");

captures.forEach((c) => {
  const id = c.id ?? `${c.slug}-${c.week}`;
  lines.push(
    `INSERT INTO captures (id,week,slug,portal,company,url,brand,r2_key,width,height,palette,analysis,analysis_by,status,captured_at) VALUES (` +
      `${q(id)},${q(c.week)},${q(c.slug)},${q(c.portal)},${q(c.company)},${q(c.url)},${q(c.brand)},` +
      `NULL,${Number(c.width ?? 1280)},${Number(c.height ?? 800)},` +
      `${q(JSON.stringify(c.palette ?? []))},${q(c.analysis ?? "")},'sample',${q(c.status ?? "ok")},${q(c.capturedAt ?? new Date().toISOString())});`
  );
});
lines.push("");

writeFileSync(OUT, lines.join("\n"));
console.log(`seed.sql: ${portals.length} portals, ${weeks.length} week(s), ${captures.length} captures`);
